stages:
  prepare_data:
    cmd: python -m src.prepare_data
    deps:
      - data/eco2mix-regional-cons-def.csv
      - src/prepare_data.py
    outs:
      - data/eco2mix.csv
      - data/eco2mix_regional.csv

  train:
    cmd: python -m src.train
    deps:
      - data/eco2mix.csv
      - src/features.py
      - src/train.py